version: 2
jobs:
  build:
    docker:
      - image: node:12

    working_directory: ~/repo

    steps:
      - checkout

      - run: yarn install

      - run: yarn add netlify-cli

      - run: yarn test

      - run: yarn build
