enum Exception {
    DEFAULT = 0,
    INPUT_NOT_VALID = 100,
    USER_NOT_FOUND = 101,
    INVALID_CREDENTIALS = 102,
    UNAUTHORIZED = 103,
    EMAIL_ALREADY_EXISTS = 104,
    USERNAME_ALREADY_EXISTS = 105,
    INVALID_ACCOUNT_TYPE = 106
}

export default Exception;